#include <iostream>
#include <string>

using namespace std;

int main(){
	string a;
	
	cout << "Enter the word you want to know:";
	cin >> a;
	
    if (a == "COMPUTER") {
        cout << "A computer is an electronic device that can receive, store, process, and output data.";
    } else if (a == "DIGITAL COMPUTER") {
        cout << "This computer is capable of processing information in discrete form. In digital technology, data in the form of letters, symbols, or numbers is presented in binary form.";
    } else if (a == "ANALOG COMPUTER") {
        cout << "These computers are used to process data generated by ongoing physical processes.";
    } else if (a == "HYBRID COMPUTER") {
        cout << "These use both analog and digital. It has the speed of analog and the accuracy of digital computers. And it is used as an effective means for complex simulation.";
    } else if (a == "SUPER COMPUTER") {
        cout << "These are the most powerful and expensive computers that are used for complex scientific calculations, simulations, and research.";
    } else if (a == "MAINFRAME COMPUTER") {
        cout << "These are large and powerful computers that are used by large organizations such as banks, airlines, and government agencies to process huge amounts of data and handle multiple users simultaneously.";
    } else if (a == "MINI COMPUTER") {
        cout << "These are smaller and less powerful than mainframes, but they are still capable of handling multiple users and processing large amounts of data.";
    } else if (a == "PERSONAL COMPUTER") {
        cout << "These are small and affordable computers that are designed for individual users.";
    } else if (a == "WORKSTATION") {
        cout << "These are high-performance computers that are used by professionals.";
    } else if (a == "EMBEDDED COMPUTER") {
        cout << "These are specialized computers that are built into other devices.";
    } else if (a == "MOBILE DEVICES") {
        cout << "These are small and portable computers that are designed for on-the-go use, such as smartphones, tablets, and laptops.";
    } else if (a == "MICRO COMPUTER") {
        cout << "These are also known as Personal Computers. These types of digital computers use microprocessors and include both desktops and laptops.";
    } else if (a == "RAM") {
        cout << "RAM is an electronic device that is faster and can match up with the CPU. It is volatile.";
    } else if (a == "HARD DISK") {
        cout << "A hard disk is an electromechanical device, and its speed is slower than RAM. It is non-volatile.";
    } else if (a == "HACKER") {
        cout << "A hacker will warn you about malicious activity going around in your computer. They will not steal your information.";
    } else if (a == "CRACKER") {
        cout << "A cracker will try to steal your information without informing you.";
    } else if (a == "SYSTEM SOFTWARE") {
        cout << "System software includes essential programs that allow a computer to function, such as the operating system.";
    } else if (a == "APPLICATION SOFTWARE") {
        cout << "Application software consists of programs that allow users to perform specific tasks, such as word processing or gaming.";
    } else if (a == "VIRUS") {
        cout << "A virus is a malicious program that can spread through email attachments and infected websites.";
    } else if (a == "ABACUS") {
        cout << "The abacus was invented by the Chinese and is believed to be the first computer. The beads are moved according to specific rules to perform arithmetic calculations.";
    } else if (a == "NAPIER'S BONES") {
        cout << "Napier's Bones is a manually operated calculating device that introduced the decimal point system for calculations.";
    } else if (a == "STEPPED RECKONER") {
        cout << "The Stepped Reckoner was a digital mechanical calculator developed by Gottfried Wilhelm Leibniz.";
    } else if (a == "ANALYTICAL ENGINE") {
        cout << "The Analytical Engine was a mechanical computer designed by Charles Babbage. It used punch cards for input.";
    } else if (a == "TABULATING MACHINE") {
        cout << "The Tabulating Machine was a mechanical device based on punch cards, used for tabulating statistics and sorting data.";
    } else if (a == "KEYBOARD") {
        cout << "A keyboard is a common peripheral device used to input text and commands into a computer.";
    } else if (a == "PERIPHERAL") {
        cout << "Peripheral devices are external hardware components that perform specific functions, such as printers and scanners.";
    } else if (a == "MONITOR") {
        cout << "A monitor is a device that visually displays output from a computer.";
    } else if (a == "BOOTING UP") {
        cout << "Booting up is the process of starting a computer by loading the operating system into memory.";
    } else if (a == "SHUTTING DOWN") {
        cout << "Shutting down is the process of properly turning off a computer after use.";
    } else if (a == "CPU") {
        cout << "The CPU (Central Processing Unit) is the main processing unit of a computer responsible for executing instructions.";
    } else {
        cout << "Try a different word.";
    }

    return 0;
}